### ISSUE TITLE
.ttl.ttl files created

### ISSUE THREAD

**Issue by michielbdejong** [ozcanseker/Social-linked-beer#1]
I now have a file https://michielbdejong.inrupt.net/settings/publicTypeIndex.ttl.ttl on my pod, somehow. Could it be that this app created that?

I moved it to https://michielbdejong.inrupt.net/settings/publicTypeIndex.ttl and then later did the same moving https://michielbdejong.inrupt.net/public/sociallinkedbeer4/appdata.ttl.ttl to https://michielbdejong.inrupt.net/public/sociallinkedbeer4/appdata.ttl and now i can log in to the app.

**Comment by ozcanseker** [comment]
Oh yes definitely.  I had some problems with creating files and now it will create a .ttl.ttl file. I know this bug and I will solve it. It is still in early development and it would be smart if i added some kind of warning. 

Thanks.
